sudo: true

install:
- curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
- ./run "docker build --rm -t akp-inference bin && docker run -i --name akp-inference akp-inference echo hello world"
