#!/bin/bash

relative_path=`dirname $0`
this_directory=`cd $relative_path;pwd`

cd $this_directory
name=akp-inference

echo "********** Building the enviroment **********"
docker build --rm -t $name .
docker rm -f $(docker ps -aq)
echo "********** Running $@ **********"
docker run -it -h $name-sandbox --name $name $name "$@"
exit_code=$(docker inspect -f {{.State.ExitCode}} $name)
message=FAIL
if [[ $exit_code -eq 0 ]]
then
	message=OK
fi
echo $message
exit $exit_code

